import localFont from "next/font/local";

import { Nav } from "@/components/ui/Nav";
import "./global.css";
import { twMerge } from "tailwind-merge";
import { HTML } from "@/components/ui/HTML";
import { ReduxProvider } from "@/components/ui/Provider";

export const metadata = {
  title: "Welcome to client",
  description: "Generated by create-nx-workspace",
};

const ubuntu = localFont({
  src: [
    {
      path: "../public/assets/fonts/Ubuntu-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/assets/fonts/Ubuntu-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/assets/fonts/Ubuntu-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/assets/fonts/Ubuntu-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxProvider>
      <HTML>
        <head>
          <link
            rel="icon"
            type="image/png"
            href="/favicon-96x96.png"
            sizes="96x96"
          />
          <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
          <link rel="shortcut icon" href="/favicon.ico" />
          <link
            rel="apple-touch-icon"
            sizes="180x180"
            href="/apple-touch-icon.png"
          />
          <meta name="apple-mobile-web-app-title" content="MyWebSite" />
          <link rel="manifest" href="/site.webmanifest" />
        </head>
        <body
          className={twMerge(
            "bg-mantis-50 dark:bg-mantis-1000 text-mantis-950 dark:text-mantis-50 flex flex-col",
            ubuntu.className
          )}
        >
          <Nav />
          {children}
        </body>
      </HTML>
    </ReduxProvider>
  );
}
